Description: RoboLedger App Service - AWS App Runner

Parameters:
  # Environment & AWS Configuration
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - staging
      - dev
    Description: Environment name (prod, staging, or dev)
    ConstraintDescription: Environment must be prod, staging, or dev

  AWSAccountId:
    Type: String
    Description: AWS Account ID for cross-account resources
    AllowedPattern: '[0-9]{12}'

  # Access Mode Configuration
  AppAccessMode:
    Type: String
    Default: public
    AllowedValues:
      - public
      - public-http
    Description: |
      App access mode:
      - public: CloudFront + custom domain + HTTPS (requires DomainName and HostedZoneId)
      - public-http: CloudFront with AWS DNS, no custom domain needed

  # Domain & DNS Configuration (required only when AppAccessMode=public)
  DomainName:
    Type: String
    Default: ''
    Description: Full domain name for the application (e.g., roboledger.ai). Required for public mode.

  HostedZoneId:
    Type: String
    Default: ''
    Description: Route53 Hosted Zone ID for the domain. Required for public mode.

  # S3 Bucket Configuration (passed from deploy-s3 workflow outputs)
  StaticAssetsBucketName:
    Type: String
    Description: S3 bucket name for static assets (from deploy-s3 workflow)

  StaticAssetsBucketArn:
    Type: String
    Description: S3 bucket ARN for static assets (from deploy-s3 workflow)

  StaticAssetsBucketDomainName:
    Type: String
    Description: S3 bucket regional domain name for static assets (from deploy-s3 workflow)

  # Container & Application Configuration
  ECRRepository:
    Type: String
    Description: ECR repository name
    Default: roboledger-app

  ECRImageTag:
    Type: String
    Description: Docker image tag
    Default: latest

  ContainerPort:
    Type: Number
    Default: 3000
    MinValue: 1
    MaxValue: 65535
    Description: Port the container listens on

  # App Runner Compute Configuration
  Cpu:
    Type: String
    Default: '0.25 vCPU'
    Description: CPU for App Runner instance
    AllowedValues:
      - '0.25 vCPU'
      - '0.5 vCPU'
      - '1 vCPU'
      - '2 vCPU'

  Memory:
    Type: String
    Default: '0.5 GB'
    Description: Memory for App Runner instance
    AllowedValues:
      - '0.5 GB'
      - '1 GB'
      - '2 GB'
      - '3 GB'
      - '4 GB'

  # Auto-scaling Configuration
  CapacityMin:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 25
    Description: Minimum number of instances for auto scaling

  CapacityMax:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 25
    Description: Maximum number of instances for auto scaling

  MaxConcurrency:
    Type: Number
    Default: 100
    MinValue: 1
    MaxValue: 200
    Description: Maximum concurrent requests per instance before scaling

  # Tagging Configuration
  ServiceTag:
    Type: String
    Default: RoboLedger
    Description: Tag value for Service identification

  ComponentTag:
    Type: String
    Default: App
    Description: Tag value for Component identification

Conditions:
  # Access mode conditions
  IsPublicMode: !Equals [!Ref AppAccessMode, 'public']
  IsPublicHttpMode: !Equals [!Ref AppAccessMode, 'public-http']

  # Production + public mode: enables www.domain.com redirect to domain.com
  IsProductionPublic: !And
    - !Equals [!Ref Environment, 'prod']
    - !Equals [!Ref AppAccessMode, 'public']

Resources:
  # ACM Certificate (only for public mode with custom domain)
  # Note: CloudFront requires certificates to be in us-east-1
  AppCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsPublicMode
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub '*.${DomainName}'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: !Ref ComponentTag
        - Key: CreatedBy
          Value: CloudFormation

  # IAM Role for App Runner to access ECR
  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      RoleName: !Sub roboledger-${Environment}-apprunner-access
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: !Ref ComponentTag
        - Key: CreatedBy
          Value: CloudFormation

  # IAM Role for App Runner instance (if app needs AWS service access)
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      RoleName: !Sub roboledger-${Environment}-apprunner-instance
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: !Ref ComponentTag
        - Key: CreatedBy
          Value: CloudFormation

  # Auto Scaling Configuration
  AppRunnerAutoScaling:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: !Sub roboledger-${Environment}-autoscaling
      MaxConcurrency: !Ref MaxConcurrency
      MaxSize: !Ref CapacityMax
      MinSize: !Ref CapacityMin
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: !Ref ComponentTag
        - Key: CreatedBy
          Value: CloudFormation

  # App Runner Service
  AppRunnerService:
    Type: AWS::AppRunner::Service
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      ServiceName: !Sub roboledger-${Environment}
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerAccessRole.Arn
        AutoDeploymentsEnabled: false
        ImageRepository:
          ImageIdentifier: !Sub ${AWSAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:${ECRImageTag}
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: !Ref ContainerPort
            RuntimeEnvironmentVariables:
              - Name: NODE_ENV
                Value: production
      InstanceConfiguration:
        Cpu: !Ref Cpu
        Memory: !Ref Memory
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /api/utilities/health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5
      AutoScalingConfigurationArn: !GetAtt AppRunnerAutoScaling.AutoScalingConfigurationArn
      NetworkConfiguration:
        EgressConfiguration:
          EgressType: DEFAULT
      ObservabilityConfiguration:
        ObservabilityEnabled: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: !Ref ComponentTag
        - Key: CreatedBy
          Value: CloudFormation

  # Bucket Policy for CloudFront Access
  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssetsBucketName
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${StaticAssetsBucketArn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  # CloudFront Origin Access Control
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub roboledger-${Environment}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub RoboLedger ${Environment} Distribution
        Enabled: true
        PriceClass: PriceClass_100 # Use only North America and Europe for cost savings
        HttpVersion: http2
        # Aliases only for public mode (custom domain)
        Aliases: !If
          - IsPublicMode
          - [!Ref DomainName]
          - !Ref AWS::NoValue
        # Certificate configuration depends on mode
        ViewerCertificate: !If
          - IsPublicMode
          - AcmCertificateArn: !Ref AppCertificate
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        DefaultRootObject: ''
        Origins:
          # Origin for static assets (S3)
          - Id: S3-Static-Assets
            DomainName: !Ref StaticAssetsBucketDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOAC
          # Origin for dynamic content (App Runner)
          # App Runner always uses HTTPS
          - Id: AppRunner-Dynamic-Content
            DomainName: !GetAtt AppRunnerService.ServiceUrl
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: AppRunner-Dynamic-Content
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled managed policy
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewerExceptHostHeader managed policy
        CacheBehaviors:
          # Cache behavior for static assets
          - PathPattern: /images/*
            TargetOriginId: S3-Static-Assets
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized managed policy
          - PathPattern: /_next/static/*
            TargetOriginId: S3-Static-Assets
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized managed policy
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: !Ref ComponentTag
        - Key: CreatedBy
          Value: CloudFormation

  # CloudFront Function for www to apex redirect
  # Only created for production + public mode (requires custom domain)
  WwwRedirectFunction:
    Type: AWS::CloudFront::Function
    Condition: IsProductionPublic
    Properties:
      Name: !Sub roboledger-app-${Environment}-www-redirect
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var host = request.headers.host.value;
          var uri = request.uri;
          var querystring = request.querystring;

          // Build the redirect URL
          var newHost = host.replace(/^www\./, '');
          var qs = '';

          // Reconstruct query string if present (URL encode to prevent malformed redirects)
          if (Object.keys(querystring).length > 0) {
            var params = [];
            for (var key in querystring) {
              var param = querystring[key];
              var encodedKey = encodeURIComponent(key);
              if (param.multiValue) {
                param.multiValue.forEach(function(v) {
                  params.push(encodedKey + '=' + encodeURIComponent(v.value));
                });
              } else if (param.value) {
                params.push(encodedKey + '=' + encodeURIComponent(param.value));
              } else {
                params.push(encodedKey);
              }
            }
            qs = '?' + params.join('&');
          }

          return {
            statusCode: 301,
            statusDescription: 'Moved Permanently',
            headers: {
              'location': { value: 'https://' + newHost + uri + qs },
              'cache-control': { value: 'max-age=31536000' }
            }
          };
        }
      FunctionConfig:
        Comment: Redirects www.roboledger.ai to roboledger.ai
        Runtime: cloudfront-js-2.0

  # CloudFront Distribution for www redirect
  # Only created for production + public mode (requires custom domain)
  WwwCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: IsProductionPublic
    Properties:
      DistributionConfig:
        Comment: !Sub RoboLedger ${Environment} WWW Redirect Distribution
        Enabled: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        Aliases:
          - !Sub www.${DomainName}
        ViewerCertificate:
          AcmCertificateArn: !Ref AppCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          # Dummy origin - required by CloudFront but never hit because the function redirects
          - Id: Dummy-Origin
            DomainName: !GetAtt AppRunnerService.ServiceUrl
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: Dummy-Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: false
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized managed policy
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt WwwRedirectFunction.FunctionARN
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: !Ref ComponentTag
        - Key: CreatedBy
          Value: CloudFormation

  # Route 53 App Domain Record (only for public mode with custom domain)
  Route53Record:
    Type: AWS::Route53::RecordSet
    Condition: IsPublicMode
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Type: A
      Name: !Ref DomainName
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's hosted zone ID
        EvaluateTargetHealth: false

  # Route 53 Record for www subdomain (only for production + public mode)
  WwwRoute53Record:
    Type: AWS::Route53::RecordSet
    Condition: IsProductionPublic
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Type: A
      Name: !Sub www.${DomainName}
      AliasTarget:
        DNSName: !GetAtt WwwCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's hosted zone ID
        EvaluateTargetHealth: false

Outputs:
  AppAccessMode:
    Description: Access mode for the application
    Value: !Ref AppAccessMode

  AppURL:
    Description: URL of the Application
    Value: !If
      - IsPublicMode
      - !Sub https://${DomainName}
      - !Sub https://${CloudFrontDistribution.DomainName}

  AppRunnerServiceUrl:
    Description: App Runner service URL (direct access)
    Value: !GetAtt AppRunnerService.ServiceUrl

  AppRunnerServiceArn:
    Description: App Runner service ARN
    Value: !GetAtt AppRunnerService.ServiceArn

  AppRunnerServiceId:
    Description: App Runner service ID
    Value: !GetAtt AppRunnerService.ServiceId

  CertificateArn:
    Condition: IsPublicMode
    Description: ACM Certificate ARN
    Value: !Ref AppCertificate

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName

  WwwCloudFrontDistributionId:
    Condition: IsProductionPublic
    Description: CloudFront Distribution ID for WWW redirect
    Value: !Ref WwwCloudFrontDistribution

  WwwCloudFrontDomainName:
    Condition: IsProductionPublic
    Description: CloudFront Distribution Domain Name for WWW redirect
    Value: !GetAtt WwwCloudFrontDistribution.DomainName

  StaticAssetsBucketName:
    Description: S3 Bucket for static assets
    Value: !Ref StaticAssetsBucketName

  Region:
    Description: AWS Region where the stack is deployed
    Value: !Ref AWS::Region

  # Access Mode Instructions
  PublicAccessInstructions:
    Condition: IsPublicMode
    Description: Instructions for accessing the app (public mode with custom domain)
    Value: !Sub |
      App is configured for public access with custom domain.

      URL: https://${DomainName}

      CloudFront Distribution: ${CloudFrontDistribution.DomainName}
      App Runner Service: ${AppRunnerService.ServiceUrl}

  PublicHttpAccessInstructions:
    Condition: IsPublicHttpMode
    Description: Instructions for accessing the app (public-http mode)
    Value: !Sub |
      App is configured for public HTTP access (no custom domain).

      URL: https://${CloudFrontDistribution.DomainName}

      This uses CloudFront's default domain with HTTPS.
      App Runner Service: ${AppRunnerService.ServiceUrl}

      LIMITATIONS (public-http mode):
      - No custom domain - uses CloudFront's d123.cloudfront.net domain
      - Some OAuth integrations may require a custom domain
